### ISSUE TITLE
Dictionary loading/lookup optimization

### ISSUE THREAD

**Issue by fireundubh** [wolfgarbe/SymSpell#16]
When you load the dictionary all at once, this can consume quite a bit of memory and is a blocking process. If the dictionary is large, this can cause responsiveness issues, assuming you don't handle that another way.

What do you think about loading the dictionary in chunks in a Lookup method? So, that alternative Lookup method would load a chunk of the dictionary, try to find a match/suggestion in that chunk, and repeat until either a match/suggestion is found or there are no more chunks to load. Effectively, you'd be streaming in the dictionary as needed, rather than loading the whole shebang into memory.

I haven't looked at the source, so I don't know if that's feasible. Maybe you need the whole dictionary loaded? That said, an index-based approach instead of chunking might even be better, [like Sphinx does](http://sphinxsearch.com/docs/current.html#indexes).

Just some thoughts.

**Comment by wolfgarbe** [comment]
I know what you mean. I'm designing large scale search engines, and there you can't load the whole Web into RAM. Instead the index is stored on disc and accessed on demand for every search query. The difference is the speed / latency. Access to disk is much slower than access to RAM. SymSpell would lose its speed. The second problem is that for every lookup SymSpell checks multiple (e.g. 25) deletes which are spread across the whole index. That would be multiple random disc accesses, and an average seek time for a single disk access is about 10 ms. That would be 250 ms for an lookup, but SymSpell can do this below 1 ms.

**Comment by dongyuwei** [comment]
@fireundubh  I have used `LMDB` instead of a Dictionary in memory, and the performance is good enough for very large words set.
see https://github.com/itslenny/SymSpell.js/issues/1

**Comment by wolfgarbe** [comment]
Thanks for the info. Good to know there is an option for very large words set.
Still, you should consider to use/port the SymSpell algorithm version 6.1 (as far as I Know both the itslenny and dongyuwei ports are based on v3.0). 
In [v5.0](https://github.com/wolfgarbe/SymSpell#changes-in-v50) and in [v6.0](https://github.com/wolfgarbe/SymSpell#changes-in-v60) there has been a 90% memory reduction as well as performance improvement and incomplete result bugs fixed.

**Comment by dongyuwei** [comment]
Thanks @wolfgarbe wol , great work!

**Comment by jalajthanaki** [comment]
> @fireundubh I have used `LMDB` instead of a Dictionary in memory, and the performance is good enough for very large words set.
> see [itslenny/SymSpell.js#1](https://github.com/itslenny/SymSpell.js/issues/1)
> 
> LMDB: An ultra-fast, ultra-compact, crash-proof key-value embedded data store.
> http://www.lmdb.tech/

@wolfgarbe: Great tool with brilliant approach...!
@dongyuwei: Your reply sounds interesting to me. I have more than 4M words in the dictionary and loading time of this dictionary and pre-calculation delete time is too high.  Here are the [more details](https://github.com/mammothb/symspellpy/issues/31). I'm using a python port `[symspellpy](https://github.com/mammothb/symspellpy)` If you can explain your approach in detail then it would be really helpful. Any suggestion or help from the community will be greatly appreciated.

**Comment by dongyuwei** [comment]
hi @jalajthanaki , I'm not familiar with python, but I think you can replace all the `dict()` to `lmdb` key-value storage. https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L56
```
self._words = dict()
self._below_threshold_words = dict()
self._deletes = defaultdict(list)
...
self._replaced_words = dict()
```
 You only need to pre-calculate the data once.

**Comment by jalajthanaki** [comment]
> hi @jalajthanaki , I'm not familiar with python, but I think you can replace all the `dict()` to `lmdb` key-value storage. https://github.com/mammothb/symspellpy/blob/master/symspellpy/symspellpy.py#L56
> 
> ```
> self._words = dict()
> self._below_threshold_words = dict()
> self._deletes = defaultdict(list)
> ...
> self._replaced_words = dict()
> ```
> You only need to pre-calculate the data once.

Thank you so much @dongyuwei for quick and useful reply

**Comment by wolfgarbe** [comment]
> I have more than 4M words in the dictionary and loading time of this dictionary and pre-calculation delete time is too high.

There are several ways you could try to improve

1. There is no no need to do  the pre-calculation of the delete structure every time the program starts. You could serialize/deserialize the delete data structure of symspell and save it to a file/load it from a file. You can implement your own serialization, use JSON or something like [flatbuffers](https://google.github.io/flatbuffers/)

2. you can speed up the precalculation time by reducing the prefixLength parameter from 7 to 5. See https://towardsdatascience.com/symspell-vs-bk-tree-100x-faster-fuzzy-string-search-spell-checking-c4f10d80a078 precalculation time for 500,000 word dictionary lp=5, lp=6, lp=7. The drawback is that the lookup time will be longer.

3. Depending on your task you should always use a maximumEditDistance as small as possible. 

```
int maxEditDistanceDictionary = 1; //maximum edit distance per dictionary precalculation
var symSpell = new SymSpell(initialCapacity, maxEditDistanceDictionary);
```

4. You could try to use the C# implementation instead of the Python implementation. C# is usually much faster than Python. But of course Python is much more popular in data science and machine learning.

5. Utilizing the pigeonhole principle by partitioning both query and dictionary terms will result in less memory consumption and 3 faster precalculation time. If you split a word with edit distance=n in two parts, one of the parts will have an edit distance<=n/2

**Comment by jalajthanaki** [comment]
@fireundubh Thank you for such an amazing inputs. I'm able to figure out how to serialize/deserialize the internal delete data structure of symspellpy. I will definitely try the other options.
