### ISSUE TITLE
c++ or python binding for SymSpell

### ISSUE THREAD

**Issue by nadavb** [wolfgarbe/SymSpell#22]
Is there a python binding for SymSpell (c++) so we can run it from Python without losing performance?

Any c/cpp porting that works?

**Comment by wolfgarbe** [comment]
There are [ports](https://github.com/wolfgarbe/SymSpell#ports) for c++ and python, both based on an early version (<=v3.0) of the SymSpell algorithm. Meanwhile [several bugs have been fixed, the lookup performance improved and the memory footprint reduced](https://github.com/wolfgarbe/SymSpell#changes-in-v61). How about IronPython, which has [support for .NET Core](https://github.com/IronLanguages/ironpython2/releases/tag/ipy-2.7.8)  or something like this:
https://stackoverflow.com/questions/2077870/how-to-load-a-c-sharp-dll-in-python
https://stackoverflow.com/questions/34266589/use-net-dll-in-python
https://stackoverflow.com/questions/7367976/calling-a-c-sharp-library-from-python

**Comment by nadavb** [comment]
Thanks. Is there an online page where we can try/test SymSpell?

**Comment by wolfgarbe** [comment]
No. But there is a demo project included in the SymSpell repository, which can be opened and built with the free [Visual Studio Code](https://code.visualstudio.com/), which runs on Windows, MacOS and Linux.

**Comment by nadavb** [comment]
Thanks. Any quality benchmarks/comparisons to Hunspell or Aspell?

**Comment by wolfgarbe** [comment]
SymSpell is an algorithm, rather than a turn-key product. It's purpose is to find all terms/candidates from a large dictionary which are within a maximum edit distance (Damerau-Levenshtein) in a very short time (to my knowledge faster than any other algorithm). The possible applications are far beyond spell checking.

For spell checking a **Weighted Edit distance*** can be added, giving a higher priority to pairs which are close to each other on the keyboard layout or which sound similar (e.g. [Soundex](https://en.wikipedia.org/wiki/Soundex) or other [phonetic algorithms](https://en.wikipedia.org/wiki/Phonetic_algorithm) which identify different spellings of the same sound). This is essentially taking into account the probabilities of which a specific errors could have been derived from each of the different suggestion candidates. This can be further extended to the context of the sentence or whole text.  It can be added as a simple post-processing step to SymSpell with only small impact on the performance by just re-prioritizing/sorting the preliminary results (candidates) according to your preferences. There is already a [SymSpell implementation with weighted Damerau-Levenshtein edit distance / keyboard-distance](https://github.com/searchhub/preDict).


>> Any quality benchmarks/comparisons to Hunspell or Aspell?
See slide 24 of the following presentation for a accuracy benchmark: http://www.mices.co/mices2017/slides/MICES2017_CXP_Andreas_Wagner_STOP-STUPID-FUZZY-SEARCHES_4x3.pdf 

>> I saw that it doesn't split words.
https://github.com/wolfgarbe/SymSpell/blob/master/README.md#compound-aware-automatic-spelling-correction
https://github.com/wolfgarbe/SymSpell/blob/master/README.md#usage-symspellcompound-demo

**Comment by nadavb** [comment]
I tried the CompoundDemo, and this indeed has the capability to break words. It works very well.
How can I change the code configuration so it will bring more than one suggestion? Currently I see that only one suggestion is brought up.

**Comment by wolfgarbe** [comment]
If you allow multiple suggestions, then the lookup time can explode:

* There are several possibilities to split a single word. 
* There are several possibilities to combine adjacent words. 
* There are several possibilities to split a single word and combine the resulting parts with adjacent words or adjacent parts of adjacent words.
* For each of the above term splitting/combinations there a multiple suggestions within the maximum edit distance .
* If you now have a sentence with e.g. 10 words, for each word all the above splitting/combining variants, and for each splitting/combining variant multiple spelling suggestions then you might end up with a combination of **hundreds of thousands of suggestions** to create, lookup and rank.

I had implemented this before, and I found that you have to know exactly what you are doing (**you may get what you wish for**). It is not practicable for a naïve use, where the user is not prepared to understand implications of suggestion combinations and will just blame it on the algorithm.
Therefore I hard wired the restriction to a single suggestion.

That said, multiple suggestions would be feasible for a single term input with just splitting (and not combining with adjacent terms) or for multiple terms if you implement a sophisticated early pruning of the variants to consider.
