### ISSUE TITLE
Phonetic Suggestions

### ISSUE THREAD

**Issue by pclancy** [wolfgarbe/SymSpell#25]
I am testing this library and need some advice as to whether this is the right tool for the job as the Top suggestion appears to be based simply on nearest match rather than any phonetic matching use by other spell checkers.  

For example, searching "kween" returns a top match of "keen".  Using Closest returns keen, tween, ween yet something like Hunspell will return Queen as the top match which is what I would expect in this case.

**Comment by wolfgarbe** [comment]
SymSpell sorts its suggestion by edit distance first, and then by word frequency. It does not implement phonetic similarity or keyboard proximity, but this can be added as a simple post-processing step.

SymSpell is an algorithm, rather than a turn-key product. It's purpose is to find all terms/candidates from a large dictionary which are within a maximum edit distance (Damerau-Levenshtein) to an input term in a very short time (to my knowledge much faster than any other algorithm). The possible applications are far beyond spell checking.

For spell checking a **Weighted Edit distance** can be added, giving a higher priority to pairs which are close to each other on the keyboard layout or which sound similar (e.g. [Soundex](https://en.wikipedia.org/wiki/Soundex) or other [phonetic algorithms](https://en.wikipedia.org/wiki/Phonetic_algorithm) which identify different spellings of the same sound). This is essentially taking into account the probabilities of which a specific errors could have been derived from each of the different suggestion candidates. This can be further extended to the context of the sentence or whole text.  It can be added as a simple post-processing step to SymSpell with only small impact on the performance by just re-prioritizing/sorting the preliminary results (candidates) according to your preferences. There is already a [SymSpell implementation with weighted Damerau-Levenshtein edit distance / keyboard-distance](https://github.com/searchhub/preDict).

SymSpell is not a replacement for Hunspell or Aspell, but it can be used as core technology to build one if speed is an issue.
