### ISSUE TITLE
Command line usage?

### ISSUE THREAD

**Issue by jmrichardson** [wolfgarbe/SymSpell#26]
Hi, 

Is there a way to use symspell from the command line?  I am not a programmer and want to use symspell without having to build a project (or use old ports).  I am on linux.  Thanks for any advice.

**Comment by wolfgarbe** [comment]
Currently symspell can't be used from the command line. SymSpell is an algorithm, rather than a turn-key spelling correction tool. It's purpose is to find all terms/candidates from a large dictionary which are within a maximum edit distance (Damerau-Levenshtein) to an input term in a very short time (to my knowledge much faster than any other algorithm). The possible applications are far beyond spell checking.

SymSpell is not a replacement for Hunspell or Aspell, but it can be used as core technology to build one if speed is an issue. For spell checking a Weighted Edit distance could be added as a simple post-processing step, giving a higher priority to pairs which are close to each other on the keyboard layout or which sound similar (e.g. Soundex or other phonetic algorithms which identify different spellings of the same sound).

While the main purpose of the SymSpell library was to showcase the speed of the algorithm and to allow an easy integration and customization, a stand alone command line version still could be useful.

What would your expect from a command line spelling correction tool? 
-Input and Output from/to standard I/O that allows pipes and redirects?
-Input and Output via text files which are specified via command line parameters?
-Input terms via command line parameter and output to standard I/O?

What's your use case?

**Comment by jmrichardson** [comment]
My use case is for OCR post cleanup.  I am using Ocropy to OCR a specific legal document which contains fields.  Unfortunately, many of the documents aren't perfectly OCR'd and would like a way to use a customized dictionary (lexicon) to correct specific misspellings or OCR errors.  I am not concerned about most English words rather specific words/fragments in the document.  For example:

> General Liability - Aggregate

This may be OCR'd to:

> Gen3erad Liabilit y - AggregateD

I would like to take a specific sentence/fragment of the document (this is part of the OCR page segmentation) and apply a customized dictionary to correct the fragment if possible.  I would like to do this using command line with any of the suggestions you made but would prefer option 1 of in/out using pipes. 

Thank you so much if you consider/decide to create or provide instructions to compile.

**Comment by wolfgarbe** [comment]
[SymSpell.CommandLine](https://github.com/wolfgarbe/SymSpell/tree/master/SymSpell.CommandLine) project added. Allows pipes and redirects for Input & Output.
Dictionary/Copus file, MaxEditDistance, Verbosity, PrefixLength can be specified via Command Line. 
No programming required.

The repository includes [compiled binaries](https://github.com/wolfgarbe/SymSpell/tree/master/SymSpell.CommandLine/bin/Release/netcoreapp2.0) and example .bat files for the use of pipes and redirects.
This Framework-dependent deployment (FDD) relies on an installed .NET Core on the target system
But you can also create a Self-contained deployment (SCD). 
See: https://docs.microsoft.com/en-us/dotnet/core/deploying/index#portable-applications.

Please let me know if this is sufficient for your use case or if there are any changes required.

**Comment by jmrichardson** [comment]
Thank you so much. I would love to test but I am on Linux.  Is there a way to get it to run on linux?

**Comment by wolfgarbe** [comment]
The [compiled binaries](https://github.com/wolfgarbe/SymSpell/tree/master/SymSpell.CommandLine/bin/Release/netcoreapp2.0) are platform independet. They are ready to be used on Linux. But you have to install the .Net core runtime first: https://docs.microsoft.com/en-us/dotnet/core/linux-prerequisites?tabs=netcore2x
And then you have to rewrite the example DOS .bat files to an equivalent Linux shell script

**Comment by jmrichardson** [comment]
Hi,

I was able to get dotnet installed on Ubuntu 16.04 and then tried to run the command-line version (based on redirect.bat) of SymSpell and got the following error:

```
john@john-XPS-8910:~/Downloads/SymSpell/SymSpell.CommandLine/bin/Release/netcoreapp2.0$ dotnet --version
2.1.4
john@john-XPS-8910:~/Downloads/SymSpell/SymSpell.CommandLine/bin/Release/netcoreapp2.0$ dotnet SymSpell.Commandline.dll load frequency_dictionary_en_82_765.txt < input.txt
No executable found matching command "dotnet-SymSpell.Commandline.dll"
```

I am not familiar with .Net and was wondering if you could point me in the right direction.

Thanks

**Comment by wolfgarbe** [comment]
You should write SymSpell.Command**L**ine.dll instead of SymSpell.Commandline.dll 
My fault. No problem on Windows, but the Linux file system is case sensitive.

**Comment by jmrichardson** [comment]
I was able to publish on Ubuntu to create SCD as you mentioned: 

`dotnet publish -c Release -r ubuntu.16.04-x64`

Then I ran a test with a modified input.txt file to test automatic compount spell correction.  Here is the input.txt file :

```
hous
inpt
in te dhird qarter oflast jear he hadlearned ofca sekretplan y iran
srry
yyyyyyy
```

And here are the results of the command line

john@john-XPS-8910:~/Downloads/SymSpell/SymSpell.CommandLine/bin/Release/netcoreapp2.0/ubuntu.16.04-x64/publish$ cat input.txt | ./SymSpell.CommandLine load ./frequency_dictionary_en_82_765.txt
Dictionary: 82,765 words, 660,957 entries, edit distance=2 in 1005.5ms 55 MB
house 1 231,310,420
input 1 57,191,675
in te dhird qarter oflast jear he hadlearned ofca sekretplan y iran 3 0
sorry 1 35,595,812
yyyyyyy 3 0


I would have expected the sentence to have the corrections made as is on your github page.  Is there something I am doing wrong?

**Comment by wolfgarbe** [comment]
The CommandLine version currently uses only Lookup(), but not LookupCompound().
But that could be easily changed.

**Lookup()** assumes every input string as single term. 

**LookupCompound()** supports compound splitting / decompounding with three cases:
1. mistakenly inserted space within a correct word led to two incorrect terms
2. mistakenly omitted space between two correct words led to one incorrect combined term
3. multiple input terms with/without spelling errors

**Comment by jmrichardson** [comment]
Hi, Yes LookupCompound sounds more like what I am looking for in my use case.  I would like SymSpell to automatically correct using the 3 items you listed on OCR text with a customized dictionary for words that are specific to the legal domain (or specifically on the OCR'd forms).  Is there something I can do to use the LookupCompound or will you be able to add that feature?

Thanks again for your help

**Comment by wolfgarbe** [comment]
As your use case is OCR post cleanup perhaps this might be of interest: [Automatic Spelling Correction: success or disaster ](https://medium.com/p/a3a6655d482a) (unfinished, unpublished draft)

**Comment by wolfgarbe** [comment]
For a quick solution just change [Line 76](https://github.com/wolfgarbe/SymSpell/blob/master/SymSpell.CommandLine/SymSpell.CommandLine.cs#L76):
from 
var suggestions = symSpell.Lookup(inputTerm, suggestionVerbosity, maxEditDistanceLookup,true);
into
var suggestions = symSpell.LookupCompound(inputTerm, maxEditDistanceLookup);

I will try to add a command line switch to choose between Lookup & LookupCompound in the next days.

**Comment by jmrichardson** [comment]
I should have the time tomorrow and will let you know how it goes.  Thanks again

**Comment by jmrichardson** [comment]
Sorry, I see that Verbosity is Top, Closest or All.  Maybe another command line argument that would only show corrected results.  Also, I don't quite understand "prefix length" argument.  Can you point me somewhere to understand what that argument does? I read from the github page that it helps with memory consumption but not quite sure of the impact on correction.

**Comment by jmrichardson** [comment]
I was also wondering if perhaps SymSpell could handle phrases.  Currently, it looks like the dictionary is for single words.  What would be really nice is the use of a lexicon of phrases as well.  For example:

```
commercial general liability
each occurence
bodily injury
```

Do you think this could be done?

**Comment by wolfgarbe** [comment]
> One suggestion, could you add the ability to only output the corrected text without any other information. Currently, it outputs information about the dictionary, entities, edit distance as well as the corrected text with number of corrections and frequency.

The information about the directory is only displayed on the console (not stdout). It will be not included if you redirect/pipe the output.

For the edit distance (it's not the number of corrections) and frequency I could implement a command line switch to suppress this information.

> Also, I don't quite understand "prefix length" argument. 

Memory consumption vs. speed trade-off. Reasonable values are 5...7. 
5: lowest memory consumption, slowest lookup
7 (default): highest memory consumption, fastest lookup
It has no impact on the correction precision or number of results.

> I was also wondering if perhaps SymSpell could handle phrases. Currently, it looks like the dictionary is for single words. 

LookupCompound handles phrases by combining them from the single words contained in dictionary.

Lookup also can already handle phrases. You can add them programmatically via symSpell.CreateDictionaryEntry("commercial general liability", 5000); 

Currently they can't be manually added to the dictionary text file with a text editor because the parsing expects the frequency number as second argument in each line. Could be changed to frequency as last argument in each line - that would allow phrases with spaces.

**Comment by wolfgarbe** [comment]
Two new CommandLine parameters have been added:
LookupType: lookup, lookupcompound, wordsegment.
OutputStats: switch to show only corrected string or including edit distance, word frequency/probability.

**Comment by ganga549** [comment]
Hi,

Is there a way to programmatically limit the number of suggestions. I have a raw txt file on which I am using SymSpell for spelling corrections. For some words, I get more than 1 suggestion. I want the TOP suggestion alone. What should I do?

**Comment by wolfgarbe** [comment]
Use verbosity=top.

**Comment by ganga549** [comment]
I have used VERBOSITY=TOP and yet it gives me 2 or 3 suggestions. If I remove the FOR loop, For Suggestion in Suggestions, it does not work. Is there a way around?
