### ISSUE TITLE
Unable to replicate spelling correction (LookupCompound) shown in README.md

### ISSUE THREAD

**Issue by mammothb** [wolfgarbe/SymSpell#39]
In SymSpell.CompoundDemo (v6.1, and v6.3),
`in te dhird qarter oflast jear he hadlearned ofca sekretplan y iran` is corrected to
`in the third quarter of last year he learned of a secret plan a iran` instead of 
`in the third quarter of last year he learned of a secret plan by iran` as shown in README.md. Note that the `y` in front of `iran` is corrected to `a` instead of `by`. 

May I know if I need to change some argument values to get the correction shown in README.md?

**Comment by wolfgarbe** [comment]
The example shown in the readme was copied from the old separate version of SymSpellCompound.
Since it had been integrated into SymSpell it uses the much newer codebase of SymSpell, which leads to the divergence. That means you are doing everything right, the example became incorrect. I'm anyway working on an improvement of the compound correction quality using Naive Bayes and Bigram probabilities. For now, "y iran" could just be removed from the example sentence.
