### ISSUE TITLE
Better explination of SuggestionStage

### ISSUE THREAD

**Issue by trans** [wolfgarbe/SymSpell#41]
I don't get the whole SuggestionStage thing. Comments say it's to help speed things up and be more memory efficient, but looking at the code I can't see how it would do anything but the opposite. Creating and populating the staging might be faster, but in the end it still has to go in the final data structure. So it's just an intermediate data object. I must be missing something.

**Comment by wolfgarbe** [comment]
While the two stage dictionary structure introduced in [v6.0](https://github.com/wolfgarbe/SymSpell#changes-in-v60) is more complex than it was previously, it offers 2x faster dictionary precalculation and 2x lower memory consumption. This has been confirmed by extensive benchmarking (you can go back to v5.1 with the single stage structure and compare it).

There are two internal delete structures. One is a staging structure that is built during a big
batch of adding words, like LoadDictionary. It uses the structure that
allows really fast construction. After all the words have been processed
into that, it blasts through that structure and incorporates it into the
permanent deletes structure. That doesn't take much time, because at that
point there is some knowledge about how many spellings there are for each
delete word. After the staging data is processed, it's thrown away. So **the
dictionary construction is fast** (stage 1), **the final internal structure is very
compact** (stage 2), and it's in a form that good for lookups (friendly to the internal
CPU cache). This scheme still allows dynamic dictionary construction. 

See the full description here:
https://github.com/wolfgarbe/SymSpell/pull/13#issuecomment-348863217
