### ISSUE TITLE
Issue with compound search

### ISSUE THREAD

**Issue by nagavardhan1** [wolfgarbe/SymSpell#49]
if I search "whatareyou" it is giving "what you"

**Comment by wolfgarbe** [comment]
[WordSegmentation vs. LookupCompound](https://towardsdatascience.com/fast-word-segmentation-for-noisy-text-2c2c41f9e8da)

**LookupCompound** can insert only a single space into a token (string fragment separated by existing spaces). It is intended for spelling correction of word segmented text but can fix an occasional missing space. There are fewer variants to generate and evaluate because of the single space restriction per token. Therefore it is faster and the quality of the correction is usually better.

**WordSegmentation** can insert as many spaces as required into a token. Therefore it is suitable also for long strings without any space. The drawback is a slower speed and correction quality, as many more potential variants exist, which need to be generated, evaluated and chosen from.

**Comment by nagavardhan1** [comment]
Is there a way I can increase it to 2 spaces instead of one?

**Comment by aashish-amber-abz** [comment]
@wolfgarbe I can't find any port in python for WordSegmentation, all the ports listed by you on the read me page is for LookupCompound. Do you know any port for WordSegmentation in python ?

**Comment by wolfgarbe** [comment]
@aashish-amber-abz No, I don't know a Python port of SymSpell which includes WordSegmentation.
But there are other word segmentation approaches in Python available (word segmentation only, without spelling correction) e.g.: https://github.com/grantjenks/python-wordsegment

**Comment by wolfgarbe** [comment]
@nagavardhan1 There is no easy way to increase the number of spaces for LookupCompound (for performance reasons). The algorithm requires significant modification. The modified algorithm, which can deal with a unlimited number of spaces to be inserted is called WordSegmentation. Please note, that it can still correct spelling errors.
