### ISSUE TITLE
How to exclude Nouns in SymSpell

### ISSUE THREAD

**Issue by larun1616** [wolfgarbe/SymSpell#55]
Is there a way to exclude nouns while correcting for spelling mistakes. When I do a spell check for a paragraph, the names also get changed into some word in the dictionary. Please let me know if there are any options available to implement this.

**Comment by wolfgarbe** [comment]
Instead excluding nouns from the query try adding them to the dictionary.

**Comment by aziesmaeili** [comment]
Is there any way to ignore some words with Symspell? We have some acronyms and we want to leave the words unchanged by spell check.

**Comment by wolfgarbe** [comment]
There is no built-in function to exclude certain words from spelling correction.

The simplest way is to add the acronyms to the dictionary (which is a simple plain text file).

Otherwise you could achieve your goal by preprocessing or modifying the code:
For SymSpell.Lookup() you can implement a preprocessing step, which prevents that Lookup is invoked for certain words.
For SymSpell.LookupCompound() you would have to modify the code of that method in a way which prevents that Lookup is invoked for certain words.
