### ISSUE TITLE
How to calculate distance manually in symspell?

### ISSUE THREAD

**Issue by MukhtarShaima** [wolfgarbe/SymSpell#60]
Greetings Sir,
I'm working on spell checker for Urdu Language.
Tried with your algorithm it gives me great results.
Now,
Can you explain how symspell algorithm works?
Like,if I wanted to calculate the edit distance of LD manual I know what's the way,
So how to calculate deletion in symspell or sympound manually,or what's the procedure for calculating manually.

Plus,I didn't got the algorithm.i know there is some deletion instead on insertion and all.
But I don't have the proper understanding of the given algorithm.
I read the algorithm written by you on medium.

**Comment by wolfgarbe** [comment]
SymSpell uses the [Damerau-Levenshtein edit distance](https://en.wikipedia.org/wiki/Damerau%E2%80%93Levenshtein_distance).

The Symmetric delete algorithm is only used as a fast and efficient pre-filter in order to reduce the number of candidates from the big dictionary. 

After this filtering step only for a very small number of candidates we need to do the (numerically expensive) calculation of the Damerau-Levenshtein edit distance.

Norvigs algorithm applies deletes, transposes, replaces and inserts operations to the **input term**, until it matches one of the dictionary terms.
SymSpell applies **only delete operations**, **but both to the input term and all dictionary terms** (the latter only once during a pre-calculation phase).

SymSpell is much faster, ss the number of possible deletes to an input term is much smaller than all possible combinations of deletes, transposes, replaces and inserts to an input term.
