### ISSUE TITLE
Non-english not working so good

### ISSUE THREAD

**Issue by emilmuller** [wolfgarbe/SymSpell#66]
I'm trying to use SymSpell on a non-English text (Norwegian). Got a good database from https://github.com/hermitdave/FrequencyWords/blob/master/content/2018/no/no_full.txt.

However, the following example does not work at all:

```
//lookup suggestions for multi-word input strings (supports compound splitting & merging)
inputTerm="dettefungererikkeveldigbra";
maxEditDistanceLookup = 2; //max edit distance per lookup (per single word, not per whole input string)
suggestions = symSpell.LookupCompound(inputTerm, maxEditDistanceLookup);

//display suggestions, edit distance and term frequency
foreach (var suggestion in suggestions)
{ 
  Console.WriteLine(suggestion.term +" "+ suggestion.distance.ToString() +" "+ suggestion.count.ToString("N0"));
}
```

Not sure if this is an error on my part, or if non-English is not supported.

I would have wished the output to be "dette fungerer ikke veldig bra", but instead I am returned with the original input.

Lookup() however, works I think.

**Comment by wolfgarbe** [comment]
SymSpell is language-independent (if you use a proper dictionary). For [word segmentation](https://github.com/wolfgarbe/SymSpell#word-segmentation-of-noisy-text) (i.e. inserting more than one space into an string) you should use symSpell.WordSegmentation(inputTerm, maxEditDistanceLookup);

Please see [WordSegmentation vs. LookupCompound](https://towardsdatascience.com/fast-word-segmentation-for-noisy-text-2c2c41f9e8da)

LookupCompound can insert only a single space into a token (string fragment separated by existing spaces). It is intended for spelling correction of word segmented text but can fix an occasional missing space. There are fewer variants to generate and evaluate because of the single space restriction per token. Therefore it is faster and the quality of the correction is usually better.

WordSegmentation can insert as many spaces as required into a token. Therefore it is suitable also for long strings without any space. The drawback is a slower speed and correction quality, as many more potential variants exist, which need to be generated, evaluated and chosen from.


Unfortunately the appropriate example was missing in the [Usage SymSpell Library](https://github.com/wolfgarbe/SymSpell#usage-symspell-library). I will add it.

**Comment by emilmuller** [comment]
Hi. Thanks for your kind response. And thanks for adding the example!
