### ISSUE TITLE
Best approach for a language that has Clitic pronouns

### ISSUE THREAD

**Issue by encrypt0r** [wolfgarbe/symspell#7]
Currently I am trying to figure out an approach to make a spell checker for [Central Kurdish](https://en.wikipedia.org/wiki/Central_Kurdish). Just like some other Indo-Europian languages, Kurdish language has Clitic pronouns. It's a bit tricky because:

- Kurdish has two sets of clitic pronouns that are used depending on the tense of the verb and whether it's transitive or not. 
- The pronouns can stick to most parts of speech: Nouns, Verbs, Adjectives and Adverbs.
- They don't always stick to the end of the word, they can also appear in the middle of the word (after the root of the verbs or after the first word of a compound word)
- There can be more than one pronoun stuck to a verb (One of them acts as a subject the other acts as an object). See example 3

Because there are two sets of pronouns, pre-calculating a dictionary with 100K words would results in about 1M words. That's before calculating the edit distances.

Which of these approaches do you think is the best in this case?
 - Compile a big dictionary with every valid combination
 - Compile a smaller dictionary composed of only the base words and categorize them and then expand each of them at run-time based on the PoS and other properties of each word.
 - Use an Recurrent Neural Network to do the job

## Examples:
*Note:* letters in bold are pronouns.

### Eat
- **I** eat => **Min** Dexo**m** [Min, m]
- **We** eat => **Ême** Dexo**yn** [Ême, yn]
- **They** eat => **Ewan** Dexo**n** [Ewan, n]

### Work
- **I** worked => **Min** Kar**m**dekird [Min, m]
- **He** Worked => **Ew** Kar**î**dekird [Ew, î]
- **They** worked => **Ewan** Kar**yan**dekird [Ewan, yan]

### Forgive
- **[You (plural)]** Forgive **me** => Bi**m**bexshi**n** [m, n]
- **[You]** Forgive **her** => B**î**bexsh**e** [î, e]
- **[You]** Forgive **them** => Bi**yan**bexsh**e** [yan, e]

**Comment by wolfgarbe** [comment]
- I recommend **approach 1**: Compile a big dictionary with every valid combination.
This allows you to use SymSpell without modification. SymSpell's speed is based on the [precalculation of all deletes](http://blog.faroo.com/2012/06/07/improved-edit-distance-based-spelling-correction/) of every word in the dictionary. 
- This would not work with **approach 2** (small dictionary of  base words). We can't  expand the base word (and create deletes) at run-time because we can't match/find the appropriate base word with the misspelled word.
- For **approach 3** (Recurrent Neural Network) see https://medium.com/@majortal/deep-spelling-9ffef96a24f6 and https://hackernoon.com/improving-deepspell-code-bdaab1c5fb7e. Your will need large datasets of kurdish text for the training phase. I expect that SymSpell would be faster, but that Deep Learning could lead to better precision by utilizing context information from the whole sentence, e.g. for choosing the right suggestion of multiple valid candidates, correcting spaces inserted into a word or spaces missing between two words.
