### ISSUE TITLE
US/UK variations

### ISSUE THREAD

**Issue by rajanand8516** [wolfgarbe/SymSpell#71]
Hi

Is there any possibilities for checking US and UK variations in SymSpell ?

**Comment by wolfgarbe** [comment]
The SymSpell algorithm itself is language independent. The language and language variants (as American and British English) solely depend und the used dictionary. 
If you want suggestions in both languages to be displayed, then you could create two SymSpell instances with different dictionaries, check the term consecutively in both instances, and aggregate the suggestions. You could also add an information for the user, to which language variant ech suggestion belongs.

Alternatively you could have both language variants in a single dictionary.   
With symSpell.Lookup(inputTerm, SymSpell.Verbosity.All, maxEditDistanceLookup); both variants would be displayed as suggestion. In order to display the user which suggestion belongs to which language variant the code has to be modified.
